; Ajustes do PHP para a Proware em produção.
date.timezone = America/Sao_Paulo
expose_php = Off
display_errors = Off
log_errors = On
error_log = /dev/stderr
session.cookie_httponly = 1
session.use_strict_mode = 1
